### ISSUE TITLE
Unknown error while processing Kovan -> Ropsten transfer

### ISSUE THREAD

**Issue by chikiru** [poanetwork/tokenbridge#598]
I built a bridge with info:
- Token bridge contract: 5.6.0
- Token bridge: 2.6.0
- BRIDGE_MODE=ERC_TO_ERC
- Home network: Kovan, Foreign network: Ropsten
I send success some tokens from the Ropsten to Kovan network.
But when I send a coin from the Home network to the Foreign network, I get an error:
```
{"level":20,"time":1631505831237,"msg":"Finished","validator":"0xb9d2F657dcB875Bf7aB1a97CeF5B72Fb33048Fd5","name":"watcher-erc-erc-collected-signatures","v":1}
{"level":50,"time":1631505831335,"msg":"Unknown error while processing transaction","validator":"0xb9d2F657dcB875Bf7aB1a97CeF5B72Fb33048Fd5","name":"watcher-erc-erc-collected-signatures","eventTransactionHash":"0x5fe50fa7b9277d33e09821a6152f5992991abe8a970d93497ce10b5086f6d22f","type":"Error","stack":"Error: Unknown error while processing message\n    at estimateGas (/mono/oracle/src/events/processCollectedSignatures/estimateGas.js:56:11)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","v":1}
```

I checked the code, and I found an error on executeSignatures function.
https://github.com/poanetwork/tokenbridge/blob/2.6.0/oracle/src/events/processAMBCollectedSignatures/estimateGas.js#L25

But I can't know why that. 
Does anyone help me?

My oracle .env
```
NODE_ENV=production
ORACLE_BRIDGE_MODE=ERC_TO_ERC
ORACLE_HOME_RPC_POLLING_INTERVAL=3000
ORACLE_FOREIGN_RPC_POLLING_INTERVAL=1000
ORACLE_ALLOW_HTTP_FOR_RPC=no
COMMON_HOME_RPC_URL=https://kovan.infura.io/v3/19b697525ea14692aa86da63e6d4cfe4
COMMON_FOREIGN_RPC_URL=https://ropsten.infura.io/v3/19b697525ea14692aa86da63e6d4cfe4

COMMON_HOME_BRIDGE_ADDRESS=0x893d1660c906c8cEf3cb63CBCE13763b4D9b4864
ORACLE_HOME_START_BLOCK=27158941
COMMON_FOREIGN_BRIDGE_ADDRESS=0x8c026C20c183c65d02b9cb96e40ec956B1636930
ORACLE_FOREIGN_START_BLOCK=11019439

ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY=#####
ORACLE_VALIDATOR_ADDRESS=0xb9d2F657dcB875Bf7aB1a97CeF5B72Fb33048Fd5

#COMMON_HOME_GAS_PRICE_SUPPLIER_URL=
#COMMON_HOME_GAS_PRICE_SPEED_TYPE=fast
#COMMON_HOME_GAS_PRICE_FALLBACK=80000000000
COMMON_HOME_GAS_PRICE_FALLBACK=62000000000
HOME_DEFAULT_GAS_PRICE=62000000000
ORACLE_HOME_GAS_PRICE_UPDATE_INTERVAL=300000
COMMON_HOME_GAS_PRICE_FACTOR=0.1

#COMMON_FOREIGN_GAS_PRICE_SUPPLIER_URL=
#COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE=fast
COMMON_FOREIGN_GAS_PRICE_FALLBACK=100000000000
FOREIGN_DEFAULT_GAS_PRICE=100000000000
ORACLE_FOREIGN_GAS_PRICE_UPDATE_INTERVAL=300000
COMMON_FOREIGN_GAS_PRICE_FACTOR=1

ORACLE_QUEUE_URL=amqp://rabbit
ORACLE_REDIS_URL=redis://redis:6379



ORACLE_LOG_LEVEL=debug
ORACLE_MAX_PROCESSING_TIME=0
ORACLE_RPC_REQUEST_TIMEOUT=50000

#ORACLE_HOME_TO_FOREIGN_ALLOWANCE_LIST=access-lists/allowance_list.txt
#ORACLE_HOME_TO_FOREIGN_BLOCK_LIST=access-lists/block_list.txt
ORACLE_HOME_TO_FOREIGN_CHECK_SENDER=false
```

**Comment by akolotov** [comment]
The `ERC_TO_ERC`bridge mode is not supported anymore. Try to use the Arbitrary Message Bridge with the OmniBridge extension.
