### ISSUE TITLE
kind of sqlite error

### ISSUE THREAD

**Issue by git-pawan-tripathi** [poanetwork/tokenbridge#645]
user@userM-I-470:~/tokenbridge(master)$ yarn initialize
yarn run v1.22.17
$ yarn clean && git submodule update --init && yarn install --unsafe-perm --frozen-lockfile && yarn install:deploy && yarn compile:contracts
$ rm -rf ./node_modules ./**/node_modules ./**/**/node_modules ./**/build ./**/**/dist
[1/4] Resolving packages...
warning Resolution field "@mycrypto/eth-scan@3.5.3" is incompatible with requested version "@mycrypto/eth-scan@3.5.2"
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > eslint-config-airbnb@17.1.0" has unmet peer dependency "eslint-plugin-import@^2.14.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@13.1.0" has unmet peer dependency "eslint-plugin-import@^2.14.0".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > @opengsn/contracts@2.2.2" has unmet peer dependency "@types/bn.js@^5.1.0".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > @opengsn/contracts@2.2.2" has unmet peer dependency "bn.js@^5.2.0".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > @opengsn/contracts@2.2.2" has unmet peer dependency "web3@^1.2.6".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > @opengsn/contracts@2.2.2" has unmet peer dependency "web3-core@^1.2.6".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > @opengsn/contracts@2.2.2" has unmet peer dependency "web3-eth-contract@^1.2.6".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > chai-bn@0.1.1" has unmet peer dependency "bn.js@^4.11.0".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > alm > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > alm > styled-components@5.1.1" has unmet peer dependency "react-is@>= 16.8.0".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > alm-e2e > jest-puppeteer@4.4.0" has incorrect peer dependency "puppeteer@>= 1.5.0 < 3".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > @codechecks/client > ts-node@8.8.2" has unmet peer dependency "typescript@>=2.7".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > truffle > @truffle/db > jsondown@1.0.0" has unmet peer dependency "abstract-leveldown@*".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > truffle > @truffle/preserve-to-buckets > ipfs-http-client > native-abort-controller@0.0.3" has unmet peer dependency "abort-controller@*".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > @opengsn/cli > @truffle/hdwallet-provider > web3-provider-engine > eth-block-tracker > @babel/plugin-transform-runtime@7.13.15" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > truffle > @truffle/db > graphql-tools > @graphql-tools/links > apollo-upload-client@14.1.2" has unmet peer dependency "subscriptions-transport-ws@^0.9.0".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > truffle > @truffle/preserve-to-buckets > @textile/hub > @textile/buckets > @improbable-eng/grpc-web@0.13.0" has unmet peer dependency "google-protobuf@^3.2.0".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > truffle > @truffle/preserve-to-buckets > @textile/hub > @textile/hub-filecoin > @improbable-eng/grpc-web@0.12.0" has unmet peer dependency "google-protobuf@^3.2.0".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > @opengsn/cli > @truffle/hdwallet-provider > web3-provider-engine > eth-block-tracker > @babel/plugin-transform-runtime > babel-plugin-polyfill-corejs2@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > @opengsn/cli > @truffle/hdwallet-provider > web3-provider-engine > eth-block-tracker > @babel/plugin-transform-runtime > babel-plugin-polyfill-corejs3@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > @opengsn/cli > @truffle/hdwallet-provider > web3-provider-engine > eth-block-tracker > @babel/plugin-transform-runtime > babel-plugin-polyfill-regenerator@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > truffle > @truffle/preserve-to-buckets > ipfs-http-client > multiaddr > dns-over-http-resolver > native-fetch@3.0.0" has unmet peer dependency "node-fetch@*".
warning "workspace-aggregator-ff9be7ed-e3fc-40f7-b40b-337d690d6999 > tokenbridge-contracts > @opengsn/cli > @truffle/hdwallet-provider > web3-provider-engine > eth-block-tracker > @babel/plugin-transform-runtime > babel-plugin-polyfill-corejs2 > @babel/helper-define-polyfill-provider@0.2.0" has unmet peer dependency "@babel/core@^7.4.0-0".
[4/4] Building fresh packages...
[11/43] ⢀ web3-shh
[2/43] ⢀ sha3
[10/43] ⢀ websocket
[8/43] ⢀ @web3-js/websocket
error /home/user/tokenbridge/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/user/tokenbridge/node_modules/sha3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.10.0 | linux | x64
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python2"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/user/tokenbridge/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/tokenbridge/node_modules/sha3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/tokenbridge/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.cache/node-gyp/14.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.cache/node-gyp/14.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/user/tokenbridge/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.cache/node-gyp/14.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user/tokenbridge/node_modules/sha3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/user/tokenbridge/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
In file included from ../src/addon.cpp:4:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../node_modules/nan/nan.h:2232:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/addon.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SHA3Hash::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cpp:49:23: warning: ‘new’ of type ‘SHA3Hash’ with extended alignment 32 [-Waligned-new=]
   49 |    obj = new SHA3Hash();
      |                       ^
../src/addon.cpp:49:23: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
../src/addon.cpp:49:23: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
../src/addon.cpp: In static member function ‘static void SHA3Hash::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/addon.cpp:83:27: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>&)’
   83 |   target->Set(className, f);
      |                           ^
In file included from /home/user/.cache/node-gyp/14.10.0/include/node/node.h:67,
                 from ../src/addon.cpp:1:
/home/user/.cache/node-gyp/14.10.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/user/.cache/node-gyp/14.10.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/user/.cache/node-gyp/14.10.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/user/.cache/node-gyp/14.10.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../src/addon.cpp:1:
../src/addon.cpp: At global scope:
/home/user/.cache/node-gyp/14.10.0/include/node/node.h:746:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  746 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/user/.cache/node-gyp/14.10.0/include/node/node.h:780:3: note: in expansion of macro ‘NODE_MODULE_X’
  780 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/addon.cpp:164:1: note: in expansion of macro ‘NODE_MODULE’
  164 | NODE_MODULE(sha3, SHA3Hash::Init)
      | ^~~~~~~~~~~
make: *** [sha3.target.mk:115: Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/tokenbridge/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.13.0-30-generic
gyp ERR! command "/home/user/.nvm/versions/node/v14.10.0/bin/node" "/home/user/tokenbridge/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/user/tokenbridge/node_modules/sha3
gyp ERR! node -v v14.10.0

warning Error running install script for optional dependency: "/home/user/tokenbridge/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/user/tokenbridge/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.10.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for \"/home/user/tokenbridge/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node\" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.10.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.10.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.10.0 | linux | x64
gyp info find Python using Python version 2.7.18 found at \"/usr/bin/python2\"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/user/tokenbridge/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/tokenbridge/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/tokenbridge/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.cache/node-gyp/14.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.cache/node-gyp/14.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/user/tokenbridge/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/user/.cache/node-gyp/14.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/user/tokenbridge/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.10.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/user/tokenbridge/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
/bin/sh: 1: python: not found
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
make: Leaving directory '/home/user/tokenbridge/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/tokenbridge/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.13.0-30-generic
gyp ERR! command \"/home/user/.nvm/versions/node/v14.10.0/bin/node\" \"/home/user/tokenbridge/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/home/user/tokenbridge/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node\" \"--module_name=node_sqlite3\" \"--module_path=/home/user/tokenbridge/node_modules/sqlite3/lib/binding/node-v83-linux-x64\" \"--napi_version=6\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v83\"
gyp ERR! cwd /home/user/tokenbridge/node_modules/sqlite3
gyp ERR! node -v v14.10.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/user/.nvm/versions/node/v14.10.0/bin/node /home/user/tokenbridge/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/user/tokenbridge/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/user/tokenbridge/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/user/tokenbridge/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1047:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 5.13.0-30-generic
node-pre-gyp ERR! command \"/home/user/.nvm/versions/node/v14.10.0/bin/node\" \"/home/user/tokenbridge/node_modules/sqlite3/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /home/user/tokenbridge/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/user/.nvm/versions/node/v14.10.0/bin/node /home/user/tokenbridge/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/user/tokenbridge/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/user/tokenbridge/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)"
info This module is OPTIONAL, you can safely ignore this error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by git-pawan-tripathi** [comment]
sorry i got that , just use node 12 if you want to use this repo
